### ISSUE TITLE
可以支持静态图片吗？

### ISSUE THREAD

**Issue by baosuyaole1** [jsxiaosi/xs-components-lib#10]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/28467941/218667172-8e136a5e-3093-43a8-95a0-aeebe39b4e67.png">

声明了图片后缀名也不可以 
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'

**Comment by jsxiaosi** [comment]
已处理
