### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by BlueBubbleWei** [jsxiaosi/xs-components-lib#12]
`
 ➜  Local:   http://localhost:3001/
  ➜  Network: http://192.168.1.23:3001/
  ➜  press h to show help
Failed to load url D:/TestPrj/xs-components-lib/dist/xs-components/es/index (resolved id: D:/TestPrj/xs-components-lib/dist/xs-components/es/index). Does the file exist?
Failed to load url D:/TestPrj/xs-components-lib/dist/xs-components/es/hooks/useDeveloper (resolved id: D:/TestPrj/xs-components-lib/dist/xs-components/es/hooks/useDeveloper). Does the file exist?
Failed to load url D:/TestPrj/xs-components-lib/dist/xs-components/es/utils/myDevelop (resolved id: D:/TestPrj/xs-components-lib/dist/xs-components/es/utils/myDevelop). Does the file exist?

`

**Comment by BlueBubbleWei** [comment]
先执行npm run docs:dev

**Comment by jsxiaosi** [comment]
你是不是直接执行了`npm run dev`，`npm run dev` 执行的是effect调试项目，里面vite.config.ts配置了引用打包目录，需要先执行一下`npm run build`，文档上没说明晚点我添加上去
