### ISSUE TITLE
npm run ct "组件"生成失败，Vitepress实例不能正常显示。

### ISSUE THREAD

**Issue by xmweijh** [jsxiaosi/xs-components-lib#4]
生成脚本template.sh判断name时[[ $NAME =~ $re ]]似乎多了一个[]。
plugins.ts返回Demo时向子组件传入了Demos，但在plugins中未定义Demos。

**Comment by jsxiaosi** [comment]
> 生成脚本template.sh判断name时[[ $NAME =~ $re ]]似乎多了一个[]。 plugins.ts返回Demo时向子组件传入了Demos，但在plugins中未定义Demos。

1、是的，多了一个[]，已经更改~！
2、Demos是在`docs/.vitepress/plugins/markdown-transform.ts`插件里面配置的，不过前段时间我修复过深层嵌套文档会导致无法正确查找到示例代码的问题，你可以拉一下最新代码看一下还能不能复现？

**Comment by xmweijh** [comment]
> > 生成脚本template.sh判断name时[[ $NAME =~ $re ]]似乎多了一个[]。 plugins.ts返回Demo时向子组件传入了Demos，但在plugins中未定义Demos。
> 
> 1、是的，多了一个[]，已经更改~！ 2、Demos是在`docs/.vitepress/plugins/markdown-transform.ts`插件里面配置的，不过前段时间我修复过深层嵌套文档会导致无法正确查找到示例代码的问题，你可以拉一下最新代码看一下还能不能复现？

看了下markdown-transform的代码原来是因为系统不同,window是'\'所以filePath.startsWith('..\\') 的判断总是false

**Comment by jsxiaosi** [comment]
> > > 生成脚本template.sh判断name时[[ $NAME =~ $re ]]似乎多了一个[]。 plugins.ts返回Demo时向子组件传入了Demos，但在plugins中未定义Demos。
> > 
> > 
> > 1、是的，多了一个[]，已经更改~！ 2、Demos是在`docs/.vitepress/plugins/markdown-transform.ts`插件里面配置的，不过前段时间我修复过深层嵌套文档会导致无法正确查找到示例代码的问题，你可以拉一下最新代码看一下还能不能复现？
> 
> 看了下markdown-transform的代码原来是因为系统不同,window是''所以filePath.startsWith('..\') 的判断总是false

好的~！晚点有空我修复，或者你可以提交pr？

**Comment by xmweijh** [comment]
好的大佬~

**Comment by jsxiaosi** [comment]
> 好的大佬~

或者你可以尝试一下获取到filePath之后把`\`替换成`/`

**Comment by xmweijh** [comment]
> 

我把他们先按照系统分隔符拆分然后统一用\/连接

**Comment by jsxiaosi** [comment]
> > 
> 
> 我把他们先按照系统分隔符拆分然后统一用/连接

已合并
