### ISSUE TITLE
首页主题无法正常显示

### ISSUE THREAD

**Issue by xmweijh** [jsxiaosi/xs-components-lib#6]
重新克隆了一次，不知道为什么出现了首页主题失效的情况
![image](https://user-images.githubusercontent.com/62172475/216824890-9ce3e463-6b71-4758-8c8d-f6981b9e9ca8.png)

**Comment by jsxiaosi** [comment]
有修改过首页的md吗？可否贴一下首页的md原码？

**Comment by xmweijh** [comment]
> 

发现了原来还是因为系统不同的原因，家里windows使用就会出现这种情况。markdown-transform.ts中combineMarkdown会查找行尾，他们的行尾序列不同所以出现了异常。

**Comment by xmweijh** [comment]
手动换一下行尾模式就行啦，感谢回答，麻烦了。

**Comment by jsxiaosi** [comment]
这个在Windows上是必现吗？

**Comment by xmweijh** [comment]
> 这个在Windows上是必现吗？

差不多必现，github没设置的话拉取和上传代会根据操作系统自动转换文档的行尾序列。转换后就不能正常查找行尾了。除非设置`git config --global core.autocrlf false`

**Comment by jsxiaosi** [comment]
> > 这个在Windows上是必现吗？
> 
> 差不多必现，github没设置的话拉取和上传代会根据操作系统自动转换文档的行尾序列。转换后就不能正常查找行尾了。除非设置`git config --global core.autocrlf false`

好的，我尝试一下之后，更新一下文档~！

**Comment by jsxiaosi** [comment]
已修复
