### ISSUE TITLE
ct指令创建的组件模板除了还要改动多个地方外，还有其他问题

### ISSUE THREAD

**Issue by zp342519261** [jsxiaosi/xs-components-lib#7]
ct指令创建的组件模板除了还要改动多个地方外，
1、创建模版名称例如叫 “test”
defineOptions({
    name: 'test',
  });
 md的案例那边的组件名是Itest。
 2、创建的模版下面的引入位置会被eslint识别报错，最好.sh文件里的模版改下位置
import tabs from './src/tabs.vue';
import { withInstall } from '../../utils/install';

**Comment by jsxiaosi** [comment]
已修复
